#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

if [ "$XDEBUG_ENABLED" = true ]; then
    echo "Enabling Xdebug"
    phpenmod xdebug
else
    echo "Disabling Xdebug"
    phpdismod xdebug
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
